export const moods = [
  {
    emoji: "😊",
    name: "Amigable",
    value: "Amigable",
    color: "bg-amber-400/20 hover:bg-amber-400/30",
  },
  {
    emoji: "🤔",
    name: "Pensativo",
    value: "Pensativo",
    color: "bg-blue-400/20 hover:bg-blue-400/30",
  },
  {
    emoji: "🎉",
    name: "Entusiasta",
    value: "Entusiasta",
    color: "bg-green-400/20 hover:bg-green-400/30",
  },
  {
    emoji: "🧐",
    name: "Formal",
    value: "Formal",
    color: "bg-gray-400/20 hover:bg-gray-400/30",
  },
  {
    emoji: "😄",
    name: "Alegre",
    value: "Alegre",
    color: "bg-yellow-400/20 hover:bg-yellow-400/30",
  },
  {
    emoji: "🤝",
    name: "Profesional",
    value: "Profesional",
    color: "bg-indigo-400/20 hover:bg-indigo-400/30",
  },
  {
    emoji: "😢",
    name: "Empático",
    value: "Empático",
    color: "bg-blue-300/20 hover:bg-blue-300/30",
  },
  {
    emoji: "🥰",
    name: "Agradecido",
    value: "Agradecido",
    color: "bg-pink-400/20 hover:bg-pink-400/30",
  },
  {
    emoji: "😐",
    name: "Neutral",
    value: "Neutral",
    color: "bg-gray-300/20 hover:bg-gray-300/30",
  },
  {
    emoji: "🤓",
    name: "Informativo",
    value: "Informativo",
    color: "bg-cyan-400/20 hover:bg-cyan-400/30",
  },
  {
    emoji: "🏛️",
    name: "Diplomático",
    value: "Diplomático",
    color: "bg-purple-300/20 hover:bg-purple-300/30",
  },
  {
    emoji: "🌟",
    name: "Inspirador",
    value: "Inspirador",
    color: "bg-yellow-300/20 hover:bg-yellow-300/30",
  },
  {
    emoji: "🙏",
    name: "Respetuoso",
    value: "Respetuoso",
    color: "bg-teal-400/20 hover:bg-teal-400/30",
  },
  {
    emoji: "💼",
    name: "Corporativo",
    value: "Corporativo",
    color: "bg-gray-500/20 hover:bg-gray-500/30",
  },
  {
    emoji: "🤗",
    name: "Acogedor",
    value: "Acogedor",
    color: "bg-orange-300/20 hover:bg-orange-300/30",
  },
  {
    emoji: "🧘",
    name: "Tranquilizador",
    value: "Tranquilizador",
    color: "bg-green-300/20 hover:bg-green-300/30",
  },
  {
    emoji: "🚀",
    name: "Motivador",
    value: "Motivador",
    color: "bg-red-300/20 hover:bg-red-300/30",
  },
  {
    emoji: "🎓",
    name: "Educativo",
    value: "Educativo",
    color: "bg-blue-500/20 hover:bg-blue-500/30",
  },
  {
    emoji: "🤝",
    name: "Colaborativo",
    value: "Colaborativo",
    color: "bg-green-400/20 hover:bg-green-400/30",
  },
  {
    emoji: "⏰",
    name: "Urgente",
    value: "Urgente",
    color: "bg-red-500/20 hover:bg-red-500/30",
  },
  {
    emoji: "🎨",
    name: "Creativo",
    value: "Creativo",
    color: "bg-purple-400/20 hover:bg-purple-400/30",
  },
  {
    emoji: "🔍",
    name: "Analítico",
    value: "Analítico",
    color: "bg-blue-600/20 hover:bg-blue-600/30",
  },
  {
    emoji: "🌱",
    name: "Alentador",
    value: "Alentador",
    color: "bg-green-500/20 hover:bg-green-500/30",
  },
  {
    emoji: "🤐",
    name: "Confidencial",
    value: "Confidencial",
    color: "bg-gray-600/20 hover:bg-gray-600/30",
  },
];
